CREATE MULTISET VOLATILE TABLE STIR_ERR_LOG_RAND AS (
    DENSE_RANK() OVER (PARTITION BY WH_CUST_NO ORDER BY PERIOD_DTE DESC) - 1 AS DET_ROW_NUM
    ,*
FROM STIR_ERR_LOG_RAND
WHERE
FILE_GENERATION_DTE >= DATE YYYY-MM-DD
)
WTIH DATA
PRIMARY INDEX()
ON COMMIT PRESERVE ROWS
;

CREATE MULTISET VOLATILE TABLE #DET_ROW_NUM_PERIOD AS (
    DENSE_RANK() OVER (PARTITION BY WH_CUST_NO ORDER BY PERIOD_DTE DESC) - 1 AS DET_ROW_NUM
    ,*
FROM STIR_DET_SENT_RAND
PERIOD_DTE >= DATE YYYY-MM-DD
)
WTIH DATA
PRIMARY INDEX()
ON COMMIT PRESERVE ROWS
;

CREATE MULTISET VOLATILE TABLE #PERIOD_ACC_COUNT AS (
    SELECT 
        WH_CUST_NO,
        PERIOD_DTE,
        COUNT(DISTINCT WH_ACC_NO) AS _ILE_
    FROM STIR_ACC_SENT_RAND
)
WTIH DATA
PRIMARY INDEX()
ON COMMIT PRESERVE ROWS
;

CREATE MULTISET VOLATILE TABLE #FINAL AS (   
    WITH ACC_CTE AS (
        SELECT 
            WH_CUST_NO,
            PERIOD_DTE,
            COUNT(DISTINCT WH_ACC_NO) AS _ILE_
        FROM STIR_ACC_SENT_RAND
        WHERE PERIOD_DTE >= DATE YYYY-MM-DD
        GROUP BY WH_CUST_NO, PERIOD_DTE
    )
    -- CREATE #FINAL TABLE COMBINING DATA
    SELECT  
        CTE._ILE_,
        DET.DET_ROW_NUM,
        DET.WH_CUST_NO AS DET_WH_CUST_NO,
        DET.PERIOD_DTE AS DET_PERIOD_DTE,
        CTE.PERIOD_DTE AS CTE_PERIOD_DTE,
        ACC.PERIOD_DTE AS ACC_PERIOD_DTE,
        CBC.PERIOD_DTE AS CBC_PERIOD_DTE,
        CAR.PERIOD_DTE AS CAR_PERIOD_DTE,
        ACC.WH_ACC_NO AS ACC_WH_ACC_NO,
        CAR.WH_ACC_NO AS CAR_WH_ACC_NO,
        CBC.WH_SECNDRY_CUST_NO AS CBC_WH_SECNDRY_CUST_NO,
        CAR.WH_SECNDRY_CUST_NO AS CAR_WH_SECNDRY_CUST_NO,
        KREL.*
    FROM #DET_ROW_NUM_PERIOD DET
    LEFT JOIN ACC_CTE CTE ON DET.WH_CUST_NO = CTE.WH_CUST_NO AND DET.PERIOD_DTE = CTE.PERIOD_DTE
    LEFT JOIN STIR_ACC_SENT_RAND ACC ON DET.WH_CUST_NO = ACC.WH_CUST_NO AND DET.PERIOD_DTE = ACC.PERIOD_DTE
    LEFT JOIN STIR_REL_SENT_RAND CBC ON DET.WH_CUST_NO = CBC.WH_CUST_NO AND DET.PERIOD_DTE = CBC.PERIOD_DTE
    LEFT JOIN STIR_ACC_REL_SENT_RAND CAR ON DET.WH_CUST_NO = CAR.WH_CUST_NO AND DET.PERIOD_DTE = CAR.PERIOD_DTE
    LEFT JOIN STIR_ERR_LOG_RAND KREL ON DET.WH_CUST_NO = KREL.WH_CUST_NO AND KREL.FILE_GENERATION_DTE = DATEADD(DAY, 1, DET.PERIOD_DTE)
)
WTIH DATA
PRIMARY INDEX()
ON COMMIT PRESERVE ROWS
;
